
<div id="main-container">
	<h1>Rentrer un nouveau produit</h1>

	<form action="creation.php" method="post">
		<label>Nom</label><input name="id"><br>
		<label>Nom</label><input name="name"><br>
		<label>Nom</label><input name="price"><br>
		<label>Nom</label><input name="photo"><br>
		<label>Nom</label><input name="description"><br>
		<label>Nom</label><input name="quantity"><br>
		<button>ajouter</button>
	</form>
</div>
<?php include'footer.phtml' ?>
