<!DOCTYPE html>
<html>
<head>
	<title>bananastore</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="../public/bananastore.css">
</head>
<body>
	<h1>Les fruits à domicile</h1>
	<header>
	<?php
	pre($_SESSION);
	?> 
		<nav>
			<ul>
				<li><a href="home.php">Accueil</a></li>
				<li><a href="login.php">s'indentifier</a></li>
			</ul>
		</nav>

		<?php
					if ($user == null) {
						
						echo "Email inconnu";
					} else {

						if ($password == $user['password']){ 
						
						$_SESSION['firstname'] = $user['firstname'];

						header('Location: product.php');
						
						exit;
						
						} else {
						echo "Bonjour".$name;
					}
				?>
}
	</header>