<?php include 'header.phtml' ?>

<h2>Liste des produits</h2>

<div id = "main-container">
	<table>
		
		<tr>
			<td></td>
		</tr>

	<?php
	$products = getProductList();
	?>
	<?php foreach ($products as $product): ?>
		<tr>
			<td>nom: <?= $product["name"]?></td>
			<td>prix: <?= $product["price"]?> cents</td>
			<td><img src= "<?= $product["photo"]?>" ></td>
			<td>description: <?= $product["description"]?></td>
			<td>quantités: <?= $product["quantity"]?></td>
			<td>stock: <?= $product["is_active"]?></td>
			<td><a href="product.php?id=<?= $product['id'] ?>">voir produit</a>
			</td>
		</tr>
	<?php endforeach; ?>
	
	</table>

</div>


<?php include'footer.phtml' ?>