
<h2>Liste des produits</h2>

<div id = "main-container">
	<table>
		<tr>
			<td></td>
		</tr>
	<?php foreach ($products as $product): ?>
		<tr>
			<td>nom: <?= $product["name"]?></td>
			<td>prix : <?= $product["price"]?> cents</td>
			<td><img src="<?= $product["photo"]?>"></td>
			<td>description: <?= $product["description"]?></td>
			<td>quantités: <?= $product["quantity"]?></td>
			<td>stock :<?= $product["is_active"]?></td>
		</tr>
	<?php endforeach; ?>
	</table>


</div>
<!-- <h2>Rentrer un nouveau produit</h2>
	<div id ="formulaire">

		<form action="creation.php" method="post">
			<label>Nom</label><input name="name"><br>
			<label>Prix</label><input name="price"><br>
			<label>Inserez l'image</label><input name="photo"><br>
			<label>Description</label><input name="description"><br>
			<label>Quantités</label><input name="quantity"><br>
			<button>ajouter</button>
		</form>
	</div> -->

<?php include'footer.phtml' ?>