<?php include 'header.phtml' ?>

<table>
	<tr>
		<td>nom: <?= $product["name"]?></td>
		<td>prix: <?= $product["price"]?> cents</td>
		<td><img src= "<?= $product["photo"]?>" ></td>
		<td>description: <?= $product["description"]?></td>
		<td>quantités: <?= $product["quantity"]?></td>
		<td>stock: <?= $product["is_active"]?></td>
		<td><a href="product.php?id=<?= $product['id'] ?>">voir produit</a>
		</td>
	</tr>
</table>


<?php include'footer.phtml' ?>